import { auth, currentUser } from '@clerk/nextjs/server';
import { Suspense } from 'react';
import { getUserBoards } from '@/app/services/actions/boardActions';
import dynamic from 'next/dynamic';
import { Spinner } from '@/components/ui/spinner';
import SearchInput from './SearchInput';
import CreateBoardComponent from './CreateBoardComponent';
import DashboardStats from './DashboardStats';
import ChangeViewButtons from '@/components/ChangeViewButtons';
import BoardsComponent from './BoardsComponent';
import { redirect } from 'next/navigation';

const UpgradeDialog = dynamic(() => import('@/components/UpgradeDialog'));

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by Amr Waheed',
};
const Page = async () => {
  const { has } = await auth();
  const hasFreePlan = has({ plan: 'free_user' });
  // const hasProPlan = has({ plan: 'pro_user' });
  // const hasEnterprisePlan = has({ plan: 'enterprise' });
  const user = await currentUser();
  if (!user) redirect('/');
  const boards = await getUserBoards(user.id);
  const canCreateBoard = !hasFreePlan || boards.length < 1;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 dark:bg-gradient-to-br dark:from-blue-950 dark:via-black dark:to-purple-950">
      <main className="container mx-auto px-4 py-6 sm:py-8">
        <div className="mb-6 flex flex-col gap-4 sm:mb-8">
          <h1 className="mb-2 text-2xl font-bold sm:text-3xl">
            Welcome back,
            {user?.firstName ?? user?.emailAddresses[0].emailAddress}! 👋
          </h1>
          <p>Here is what&lsquo;s happening with your boards today.</p>
        </div>
        {/* stats */}
        <Suspense
          fallback={
            <div className="flex items-center justify-center">
              <Spinner size="xl" variant="ring" />
            </div>
          }
        >
          <DashboardStats />
        </Suspense>
        {/* Boards */}
        <div className="mb-6 sm:mb-8">
          <div className="mb-4 flex flex-col space-y-4 sm:mb-6 sm:flex-row sm:items-center sm:justify-between sm:space-y-0">
            <div>
              <h2 className="text-2xl font-bold sm:text-2xl">Your Boards</h2>
              <p className="text-gray-600 dark:text-gray-300">
                Manage Your Projects and Tasks
              </p>
              {hasFreePlan && (
                <p className="text-sm text-gray-400">
                  Free Plan: {boards.length} / 1 boards used
                </p>
              )}
            </div>
            <div className="flex flex-col items-stretch gap-2 space-y-2 sm:flex-row sm:items-center sm:space-y-0">
              <ChangeViewButtons />
              {/* <Button variant={'outline'} size={'sm'}>
                <Filter />
                Filter
              </Button> */}
              <CreateBoardComponent canCreateBoard={canCreateBoard} />
            </div>
          </div>
          <SearchInput />
          <Suspense
            fallback={
              <div className="flex items-center justify-center">
                <Spinner size="xl" variant="ring" />
              </div>
            }
          >
            <BoardsComponent />
          </Suspense>
        </div>
        <UpgradeDialog />
      </main>
    </div>
  );
};

export default Page;
